// =============================================
// script.js — handles sketch switching,
// localStorage, and metadata display
//! DO NOT EDIT THIS FILE
// =============================================

// The three sketch options and their iframe sources
const sketchFiles = {
  remix:   "switching/remix.html",
  sketch1: "switching/sketch1.html",
  sketch2: "switching/sketch2.html"
};

// Grab the elements we need
const dropdown = document.getElementById("sketch-select");
const iframe   = document.getElementById("sketch-frame");


// Load the sketch into the iframe and update the metadata display
function loadSketch(key) {
  // Update the iframe src — this reloads the sketch fresh
  iframe.src = sketchFiles[key];

  // Save the current choice to localStorage so it persists on reload
  localStorage.setItem("activeSketch", key);
}

// When the dropdown changes, load the selected sketch
dropdown.addEventListener("change", () => {
  loadSketch(dropdown.value);
});

// On page load, restore the last selected sketch (or default to remix)
const saved = localStorage.getItem("activeSketch") || "remix";
dropdown.value = saved;
loadSketch(saved);
